name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]  # Specify the Python versions you want to test

    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Clear Cache
        run: docker-compose run --rm app sh -c "rm -rf /path/to/cache/directory"

      - name: Upgrade pip
        run: docker-compose run --rm app sh -c "pip install --upgrade pip"

      - name: Install or upgrade dependencies
        run: docker-compose run --rm app sh -c "pip install --upgrade -r requirements.txt"

      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
